name: Deploy
run-name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./app

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          working_directory: ./app
      - name: Install python
        run: uv python install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # Authenticates with ECR and returns the registry URL for building images

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          REQUIREMENTS_FILE: ${{ secrets.REQUIREMENTS_FILE }}
        run: |
          # Build Docker image from Dockerfile in repository root
          mise run build
          # Push the built image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Output the full image URI for the next step
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    #   - name: Deploy Lambda function with container image
    #     uses: aws-actions/aws-lambda-deploy@v1.1.0
    #     with:
    #       function-name: my-container-function
    #       package-type: Image # Required: Indicates container deployment (not zip)
    #       image-uri: ${{ steps.build-image.outputs.image }} # ECR image URI from previous step
